AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Content Distribution'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - staging
      - production
    Default: staging
    Description: Environment that can be added to resource names

Resources:
  ContentsBucket:
    DeletionPolicy: 'Delete'
    Metadata:
      Comment: 'Bucket to store distribution content data for distribution output producer'
    Properties:
      AccessControl: 'Private'
      BucketName: !Sub 'ce-contents-${AWS::StackName}-${AWS::AccountId}'
    Type: 'AWS::S3::Bucket'

  ContentsBucketPolicy:
    Metadata:
      Comment: 'Bucket policy to allow cloudfront to access the data for content distribution'
    Properties:
      Bucket: !Ref ContentsBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${ContentsBucket}/*'
    Type: 'AWS::S3::BucketPolicy'

  CfDistribution:
    Properties:
      DistributionConfig:
        Comment: !Sub '${Environment} - Content Distribution'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: false
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000
          MinTTL: 86400
          TargetOriginId: MainOrigin
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http1.1'
        IPV6Enabled: false
        Origins:
          - DomainName: !GetAtt ContentsBucket.DomainName
            Id: MainOrigin
            OriginPath: ''
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CfOriginAccessIdentity}'
        PriceClass: 'PriceClass_All'
    Type: 'AWS::CloudFront::Distribution'

  CfOriginAccessIdentity:
    Metadata:
      Comment: 'Access S3 bucket content only through CloudFront'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access S3 bucket content only through CloudFront'
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'

Outputs:
  ContentsBucket:
    Description: 'CE Book Contents S3 Bucket'
    Value: !Ref ContentsBucket
  CfDistributionId:
    Description: 'ID for our cloudfront distribution'
    Value: !Ref CfDistribution
  CfDistributionDomainName:
    Description: 'Domain name for our cloudfront distribution'
    Value: !GetAtt CfDistribution.DomainName

